### ISSUE TITLE
Error While Sending Message : FABRIC_E_TIMEOUT

### ISSUE THREAD

**Issue by mholo65** [Azure/service-fabric-issues#129]
My application (running in Azure) randomly stopped working, getting TimeOutExceptions.

Looking into events on the Nodes I can see loads of these events:
```
Log Name:      Microsoft-ServiceFabric/Admin
Source:        Microsoft-ServiceFabric
Date:          1/16/2017 5:51:57 AM
Event ID:      44289
Task Category: FabricTransport
Level:         Warning
Keywords:      Default
User:          NETWORK SERVICE
Computer:      nt1vm000006
Description:
Error While Sending Message : FABRIC_E_TIMEOUT
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-ServiceFabric" Guid="{CBD93BC2-71E5-4566-B3A7-595D8EECA6E8}" />
    <EventID>44289</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>173</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000001</Keywords>
    <TimeCreated SystemTime="2017-01-16T05:51:57.220820200Z" />
    <EventRecordID>18205</EventRecordID>
    <Correlation />
    <Execution ProcessID="21200" ThreadID="9800" />
    <Channel>Microsoft-ServiceFabric/Admin</Channel>
    <Computer>nt1vm000006</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="id">
    </Data>
    <Data Name="type">ServiceCommunicationClient</Data>
    <Data Name="text">Error While Sending Message : FABRIC_E_TIMEOUT</Data>
  </EventData>
</Event>
```

Googling gives me this thread http://stackoverflow.com/questions/40405876/service-fabric-actor-or-service-becomes-inaccessible-at-random-after-upgrading-t

The above thread says I should add **port="0"** to the **ActorServiceEndpoint** in the ServiceManifest. But I'm also getting these issues with Stateful Services, should I add same **port="0"** to the **ServiceEndpoint** ServiceManifest?

**Comment by VipulM-MSFT** [comment]
The issue affects default Fabric Transport used by the Service Remoting stack. So if you are using the Service Remoting (IService/ServiceProxy) in your service, then yes you can specify port 0 for the Service Endpoint. This issue has been fixed in the upcoming release of Service Fabric.

**Comment by mholo65** [comment]
Thanks for the clarification!

**Comment by mholo65** [comment]
@VipulM-MSFT still seeing the same issue after setting port 0 for all endpoints used for Service Remoting. Should I also set port 0 for Replicator Endpoints?

**Comment by VipulM-MSFT** [comment]
What version of runtime and SDK are you using? Are you seeing in the issue on local machine or in Azure?

**Comment by mholo65** [comment]
Runtime version; 5.4.145
SDK version: 2.4.145

I'm only seeing this in Azure. Haven't been able to reproduce on local machine (1 Node, development cluster).

It is not consistent for every call using Service Remoting, but once occurred, it will start occurring more and more until I remove the application and redeploy. After redeployment, application will work for some while, but sooner or later I will hit a timeout.

If you need any diagnostics logs, I would be more than happy to share them with you.

**Comment by VipulM-MSFT** [comment]
If you have changed all of the ports that use remoting to 0, this should go away. Which means it might be a different issue.

Since you mentioned that you can redeploy the application, can you try the following before we go down to logs? This is to narrow down the issue. 

**Option - 1 Use WCF Service Remoting provider**
-	Import  Microsoft.ServiceFabric.Services.Wcf and Microsoft.ServiceFabric.Services.Actors.Wcf packages
-	Declare the attribute to use Actor or Services remoting provider. For example, the below code shows using the WCF Actor Remoting provider with the open timeout of one second which will fail the open and force the re-resolve if connection is not successful in 1 second. This does not change any operation timeout just the connection timeout.
[assembly: Microsoft.ServiceFabric.Actors.Remoting.Wcf.WcfActorRemotingProvider(OpenTimeoutInMilliSeconds = 1000)]
-	There is a similar attribute for the WcfServiceRemotingProvider for ServiceProxy / IService. You can verify that you are using the WCF provider by looking at the primary address in SFX. It should be net.tcp://…

**Option-2 Use a specific port for the remoting listener**
Rather than 0 specify a fixed port for all of the service endpoints. It should be outside of the application and ephemeral port ranges defined in the cluster manifest.

**Comment by NickDarvey** [comment]
@mholo65 we're having the same issue. Did @VipulM-MSFT's Option 2 work for you?

**Comment by NickDarvey** [comment]
> If you have changed all of the ports that use remoting to 0
@VipulM-MSFT should this include the `MyActorServiceReplicatorEndpoint` endpoint?

**Comment by VipulM-MSFT** [comment]
No the replicator ports should remain without the specification.

**Comment by NickDarvey** [comment]
Hi @VipulM-MSFT, any word on a fix for this? I think we just ran into this issue again.
We hadn't experienced this problem after specifying port 0, but then added new services were (not using port 0) and started experiencing it again.

**Comment by VipulM-MSFT** [comment]
Yes it should be there shortly. The upgrades are in progress.

**Comment by VipulM-MSFT** [comment]
@NickDarvey This should be now fixed. Version 5.5.216 is released: https://blogs.msdn.microsoft.com/azureservicefabric/2017/03/23/release-of-sdk-2-5-216-and-runtime-5-5-216-for-windows/

Please verify and close the issue.

**Comment by vturecek** [comment]
Closing this out, feel free to re-open if you run into it again.

**Comment by mcsdodo** [comment]
I'm having this issue too. Service randomly stops working. Cluster with 6.3.187.9494
and application with 6.3.176 packages.
