### ISSUE TITLE
ReplicatorLog is unreasonably large single file (8GB in 12hrs)

### ISSUE THREAD

**Issue by TarasRoshko** [Azure/service-fabric-issues#138]
Deployed stateful service which does not write _any_ state right now (no data whatsoever) , logged into a node, `D:\SvcFab\ReplicatorLog\replicatorshared.log` is 8GB. I mean there's nothing to replicate, I can hardly imagine reading this log to figure out any actual issues.

Tried to `cat -Tail 100`, but the file is exclusively locked which is very weird choice for a log file (how are you supposed to read such file)?

**Comment by masnider** [comment]
This log isn't the log you think it is. This is the shared _transaction_ log that gets created to back any reliable collections for that stateful service. If you want to change it:

<Section Name="KtlLogger"> 
     <Parameter Name="SharedLogSizeInMB" Value="4096"/>
   </Section>

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-configuration

**Comment by TarasRoshko** [comment]
I stand corrected, based on the file name I thought it's replication service log, not the actual transaction log, my bad

**Comment by masnider** [comment]
No problem. It is confusingly named. We also don't expect people to poke around the innards too much :)

**Comment by mleyb** [comment]
can i just get clarity on where this setting

  <Section Name="KtlLogger">
    <Parameter Name="SharedLogSizeInMB" Value="4096"/>
  </Section>

should be configured?

using Get-ServiceFabricClusterManifest on my standalone cluster, the manifest has no "KtlLogger" section in it

**Comment by masnider** [comment]
@mleyb yes you would have to add it

**Comment by ericksond** [comment]
Can't this value be changed through the template? It makes it very hard to use service fabric on typical VM sizes as it breaks upgrades once the disk is full

**Comment by mleyb** [comment]
@masnider can you provide an example of exactly how this would be done? The article linked to is light on detail and not very clear on this tbh

**Comment by masnider** [comment]
Add this to your cluster resource's arm template document and post it back to the cluster, or use the portal to add a parameter with the same name and value. Since you probably already have a fabricSettings section, just add the ktl section and the matching parameter segment. 

```json
"fabricSettings": [
  {
    "name": "KtlLogger",
    "parameters": [
      {
          "name": "SharedLogSizeInMB",
          "value": "4096"
      }
    ]
  }
]

```

**Comment by mleyb** [comment]
Brilliant! Thanks @masnider - this is much appreciated :)

**Comment by msfussell** [comment]
And just to double down on our customer appreciation, I updated the docs here https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-configuration  and here https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-manifest with this feedback. You will see the update in a couple of days.

**Comment by bshannahan-amadeus** [comment]
I am having this same issue, but the fix listed above didn't resolve the problem.  Per https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-configuration, I added the following lines to my C:\SfDevCluster\Data\clusterManifest.xml file:

`    <Section Name="KtlLogger">
      <Parameter Name="SharedLogSizeInMB" Value="1024"/>
      <Parameter Name="WriteBufferMemoryPoolMinimumInKB" Value="1024" />
      <Parameter Name="WriteBufferMemoryPoolMaximumInKB" Value="1024" />
      <Parameter Name="SharedLogId" Value="{7668BB54-FE9C-48ed-81AC-FF89E60ED2EF}"/>
      <Parameter Name="SharedLogPath" Value="D:\SharedLog.Log"/>
    </Section>	
`
These were added inside the <FabricSettings> section.

However, none of these settings appear to be read - the shared log file does not change location (It's still on my horribly cramped C drive instead of my nice large D drive) and it's still enormous (8 gigabytes, by far the largest file on that drive).  Any help on this would be greatly appreciated.

**Comment by sahebg** [comment]
Please go through this post for a permanent solution to this tiring problem. [How to Change Servcie fabric Replicator Log Size and Drive](https://sahebg.github.io/computersceince/how-to-change-azure-service-fabric-replicator-log-size-drive/).

Hope this Helps .

**Comment by IgorYastrebov** [comment]
@sahebg, the link in your post is not relevant, it is about LOCAL SF cluster, we have problem with real Azure SF cluster. That replicatorshared.log file looks to stick to static 8Gb... :(

And another finding to share:
I have A2_v2 image for primary node type. It supposes to have 20Gb for disk D:
login into VM, open explorer and calculate the real situation:
* total size = 20Gb indeed
* free space = 2 Gb
* used space = 14 Gb (14+2 = 16)
* where other 4 Gb goes for???

**Comment by sahebg** [comment]
@IgorYastrebov Hi Igor, I am sorry that my post didn't help. However, if you see from top of this thread, you will find that it was all about LOCAL SF CLUSTER. No one mentioned about Azure real SF. Therefore the link is relevant to this thread, but may be to your problem :)

Now , coming to your problem; I think still there is a way to Change the SharedLogSize in real SF Cluster as well. My suggestion is that you go through this guide from Microsoft[Customize Service Fabric cluster settings and Fabric Upgrade policy](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-fabric-settings) and check ktlLogger section. This changes should be in same format as mentioned in my [blog.](https://sahebg.github.io/computersceince/how-to-change-azure-service-fabric-replicator-log-size-drive/)

Changing this settings might come little tricky but I believe its viable. I will still suggest to Scale up your Cluster if you can afford. That 4GB mostly goes to OS , and System files.

 Let me know if you are able to successfully change and get the result. We will post your changes into  a new relevant thread.

**Comment by IgorYastrebov** [comment]
Hello Saheb, thx for the reply
"D:\SvcFab\.." is about Azure cluster location. Local location goes under "C:\SfDevCluster\.."
mentioned msdn link is about File System Limit for D:\SvcFab\Log\ filder not for D:\SvcFab\ReplicatorLog\replicatorshared
mentioned blog post is again about local cluster

I tried all mentioned cluster settings already - no one can shrink 8 Gb replicatorshared file, even I do not need for statefull services :)
What I did not try is to re-create cluster with mentioned cluster settings, will try this week maybe...

thx again

**Comment by kristofdaems** [comment]
@IgorYastrebov Did you try to re-create the cluster? What was the outcome?
We're suffering a similar problem and want to be sure it works before I re-create the cluster

Thanks

**Comment by IgorYastrebov** [comment]
ok, I've fixed several (different but related) problems.
I have several clusters (production: 7 nodes with Silver durability; dev: 3 nodes on Bronze). For some reason a cluster on 3 nodes takes tooooo long (up to 30 hours sometimes but usually 4-6 hours) to apply every settings change. This is important, be patient! 7 A4_v2 nodes takes 1-2 hour to apply a setting.
Now, there are several problems with disk space on AZURE CLUSTER (I did not faced with local cluster problems):
1) problem with Statefull service State Replica size - that D:\SvcFab\ReplicatorLog\replicatorshared file. It is always 8 Gb. This article https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-configuration saying that KtlLogger/SharedLogSizeInMB setting is responsible for the State Replica. But my experience saying - NONE of my Azure cluster reacts on this setting. Even I do NOT have any restFULL service! :) looking for another SF firmware patch.
2) problem with Logs and Telemetry logs. The folder *cluster/Log/** can grow as well. It has several inner folders for technical log, for telemetry log replicas, and other things. Telemetry log replicas are managed by Diagnostics/MaxDiskQuotaInMB setting, default value is somewhat about 65000. 65 Gb for telemetry! While we using 20-50 Gb HDD for nodes :). As soon as disk D: has less than 1 Gb free space, the Node becomes yellow and in about 5 minutes, SF delete several telemetry files and the node get back to a green state. But even that yellow icons looks scary. So I configured like this:
      {
        "name": "Diagnostics",
        "parameters": [
          {
            "name": "MaxDiskQuotaInMB",
            "value": "1024"
          }
        ]
      },
1024 Mb is enough for 1 day telemetry.
3) problem with applying a cluster setting. You can change it from portal (SF Settings menu) and from resources.azure.com, select the cluster, change xml. Do not forget to DELETE empty placeholder before POST:
      {
        "name": "(String)",
        "parameters": [
          {}
        ]
      }
Otherwise you will get Error response.
Another mistake can happen after successful POST: cluster goes into "updating" mode (properties/provisioningState path). While a cluster is that state you stop seeing your setting. If you make another change, it will discard the original one. So, a clue is: add a setting (one or several), POST changes, get green response, GET settings again, ensure the cluster goes into right "updating" state. Wait until it gets back to "Ready" state (several hours usually), check updated settings.

**Comment by igorkass** [comment]
@sahebg Hello Saheb!

I've tried to apply new settings according to this guide:

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-fabric-settings

Sadly, a new section just disappears right after I initiate the PUT request. Please note that the section KtlLogger is not available for editing through the portal:

![image](https://user-images.githubusercontent.com/10614474/37406916-6e6d4920-27a9-11e8-807f-1c8bb5991f67.png)

I suppose that it's not customizable actually. Could you update the documentation appropriately?

Thanks!

**Comment by ojasp** [comment]
I need this in the new portal as well, any updates @sahebg ?

**Comment by ddunets-softheme** [comment]
>    Another mistake can happen after successful POST: cluster goes into "updating" mode (properties/provisioningState path). While a cluster is that state you stop seeing your setting. If you make another change, it will discard the original one. So, a clue is: add a setting (one or several), POST changes, get green response, GET settings again, ensure the cluster goes into right "updating" state. Wait until it gets back to "Ready" state (several hours usually), check updated settings.

Do I need to upgrade the cluster configuration with PowerShell as it's mentioned here https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/service-fabric/service-fabric-cluster-upgrade-windows-server.md#upgrade-the-cluster-configuration?

**Comment by ddunets-softheme** [comment]
Figured out by myself. After successful PUT from Azure Resource Explorer there is an 'Updating' info message appears at Azure Service Fabric cluster overview page. Another helpful 'Create or Update Cluster' message with 'Accepted' status appears at Activity log page.
