### ISSUE TITLE
Service locking its own PDBs

### ISSUE THREAD

**Issue by andyrooger** [Azure/service-fabric-issues#150]
Raised to continue [this SO post](http://stackoverflow.com/questions/41746210/why-does-my-service-fabric-code-lock-its-own-pdbs).

In a Fabric application containing a couple of stateless services and a single stateful one, the PDBs for the stateful service keep getting locked by the service itself, resulting in failed builds with the message:

> Cannot open 'C:\\src\\ServiceFabricPDBLockingRepro\\LockingService\\obj\\x64\\Debug\\LockingService.pdb' for writing -- 'The process cannot access the file 'C:\\src\\ServiceFabricPDBLockingRepro\\LockingService\\obj\\x64\\Debug\\LockingService.pdb' because it is being used by another process.'

Minimal reproduction is at: https://github.com/andyrooger/ServiceFabricPDBLockingRepro

1. Clone this repo
2. Open the sln in Visual Studio, set the platform to *x64* and the configuration to *Debug*
2. Right click and publish the SF project
3. Right click the the SF project and rebuild
4. Observe the error above, and the following output from [handle](https://technet.microsoft.com/en-us/sysinternals/handle.aspx)
    > C:\\...\\Handle>handle "C:\\src\\ServiceFabricPDBLockingRepro\\LockingService\\obj\\x64\\Debug\\LockingService.pdb"
    > 
    > Nthandle v4.1 - Handle viewer
    > Copyright (C) 1997-2016 Mark Russinovich
    > Sysinternals - www.sysinternals.com
    > 
    > LockingService.exe pid: 12208  type: File           358: C:\\src\\ServiceFabricPDBLockingRepro\\LockingService\\obj\\x64\\Debug\\LockingService.pdb
    > LockingService.exe pid: 4996   type: File           350: C:\\src\\ServiceFabricPDBLockingRepro\\LockingService\\obj\\x64\\Debug\\LockingService.pdb
    > LockingService.exe pid: 7764   type: File           348: C:\\src\\ServiceFabricPDBLockingRepro\\LockingService\\obj\\x64\\Debug\\LockingService.pdb

In this reproduction, hitting rebuild a second time will fix the issue. However in my original project no amount of rebuilds seem to help - I have to manually stop the application running first. I also noticed as I was cutting out projects from the solution to get to something I could share, the number of rebuilds needed was reducing - so with a few more of the original projects inside the solution, I need to rebuild 4 or 5 times to get rid of the error.

**Comment by MikkelHegn** [comment]
Thanks for opening the issue. We will investigate.

**Comment by MikkelHegn** [comment]
@andyrooger I'm not able to repro based on the steps you've provided above, using your solution provided. However we do have another bug with locking .pdb files that we are investigating. I'll sync up with our devs to see if the above could be the same scenario.

**Comment by andyrooger** [comment]
@MikkelHegn Interesting, thanks for investigating. I guess I missed out a fair bit of information that may or may not be helpful:

* Using Visual Studio 2015 Update 3
* Using Windows 10
* Microsoft Azure Service Fabric version 5.4.145.9494
* Microsoft Azure Service Fabric SDK version 2.4.145.9494
* Microsoft Azure Service Fabric Tools for Visual Studio version 1.4.41209.1
* Deploying to both 1 and 5 node local dev clusters causes this on my machine
* I've asked a colleague to run the steps on another machine and he gets the same behaviour - so it's not my machine specifically but may be something to do with how we set up our company machines.

I also noticed I left an attempted workaround in the repro, which didn't work. I've removed that.

Let me know if there's anything else I can provide or test to help diagnose this.

**Comment by MikkelHegn** [comment]
Could it be the service running in the cluster that is throwing exceptions? One user commented on SO: 

> "Could it be stack trace resolution? When you throw an exception, or otherwise ask for a stack trace, doesn't .NET automatically look for PDBs to see if it can insert line numbers into the stack frames? "

**Comment by andyrooger** [comment]
It's certainly possible that's why they're locked - I do get exceptions raised as the application is first loaded, before I hit the minimum replicas. Unfortunately I can't find much information on how this works though, leaving two questions:

* *Why are the PDBs not released once they're not needed?* - this may well be a question way outside the scope of SF
* *Why are the PDBs situated in the same directory as the running EXEs not being used?* From everything I've read, this should be the first place searched for PDBs

**Comment by SergeiIsayeu** [comment]
@MikkelHegn We also have the same problem with the I think latest or close to latest Service Fabric. PDB files are locked by Service Fabric (not other apps, Service Fabric it is).
Is there a workaround to make it to not lock files or unlock them on demand?

**Comment by MikkelHegn** [comment]
@andyrooger I still cannot repro this issue using your repo.

Can you try to do a dump of the service locking the .pdb file once it's up and running? You could use Process Explorer to create a full dump of the process.

**Comment by dmaltsiniotis** [comment]
Unfortunately I have to add to this issue as well. I'm experiencing exactly what @andyrooger is, and it started immediately after upgrading Service Fabric SDK from 5.2 to the latest 5.4. My workaround has been to right click the service manager and reset my local cluster after every single deploy so I can rebuild the project again.

When debugging with Visual Studio, I see that VS is properly hooked into the PDBs, but I also see that actor services themselves (the executibles) are also hooked into their own PDBs and won't release them, ever (hence the need to kill them my resetting the local cluster.)

handle.exe reports the service itself is holding on to its own PDB (also in Release mode!)
`Company.Project.Services.Service1.exe pid: 37048  type: File           33C: S:\Company.Project.Services\Company.Project.Services.Service1\obj\x64\Debug\Company.Project.Services.Service1.pdb`

**Comment by MikkelHegn** [comment]
Thanks for adding to this @dmaltsiniotis - I've involved some more people to try at least getting this reproduced.

**Comment by andyrooger** [comment]
@MikkelHegn I have a full dump for you (54Mb zipped). What's the best way to get it to you? - I'd rather not put it into the public repo as I have no idea what's in it.

I've tried updating to the versions released a couple of days ago (5.4.164 and 2.4.164) and see the same behaviour.

I've also checked, just to be sure, that the pdb in the directory with the running service is identical to the one that gets locked in my obj directory (it is).

**Comment by andyrooger** [comment]
@SergeiIsayeu I noticed I still seem to be able to move the PDBs, even though the build won't overwrite them directly. They stay locked but it might let you build again if you script it into the build. I've had mixed results trying to do this though.

**Comment by MikkelHegn** [comment]
@andyrooger - send a mail to mikhegn@microsoft.com - I'll send back instructinos.

**Comment by dbreshears** [comment]
@andyrooger.   I am able to repro the issue.   Will investigate and see what we uncover.

**Comment by MikkelHegn** [comment]
Hi all, a quick update.

At this point we have a consistent repro and workaround, which is tied to the Network Service accounts permissions to the pdb file.
What's happening is that the service exe is not finding the pdb in locations where it's searching, causing it to fall back to loading the pdb in the directory where it was build. If the Network Service have access to the folder in which the pdb was build, it will take a lock on the file.
A current workaround at this point in time would be to restrict the Network Service access to the pdb in the build folder (obj\x64\Debug\).

We'll get more updates when we know hos to actually fix this.

**Comment by dmaltsiniotis** [comment]
This workaround has saved me a TON of time over the last two weeks developing and deploying/debugging a very large service fabric project, thank you @MikkelHegn.

**Comment by GavinSutherland** [comment]
Hi @MikkelHegn 

We are experiencing this issue also and have a couple questions related to the workaround mentioned above.

> A current workaround at this point in time would be to restrict the Network Service access to the pdb in the build folder (obj\x64\Debug).

1. Is the above quote saying that the Network Service user gets no access to the debug folder(s)? Or some other level of access?
2. We have the 'Microsoft Service Fabric Host Service' running under a specific user account rather than Network Service. We're doing this for SQL access as DBAs not keen on adding Network Service user as a SQL login. For this workaround would we need to instead add the restriction for the user account the  'Microsoft Service Fabric Host Service' is running under?

Thanks,
Gavin

**Comment by MikkelHegn** [comment]
@GavinSutherland For 1 - Yes - no access - for 2. Why do you need SF to run under different credentials, you can just have the relevant services running as another user: http://stackoverflow.com/questions/39126630/how-to-run-a-service-fabric-application-with-different-security-permissions

**Comment by ciechowoj** [comment]
> A current workaround at this point in time would be to restrict the Network Service access to the pdb in the build folder (obj\x64\Debug).

@MikkelHegn 
Could you give more details how to do that (for person who doesn't have much experience with user accounts and access rights on Windows)?

**Comment by MikkelHegn** [comment]
@ciechowoj - if you save your solution in a folder under %userprofiles% it should be good.

To set fil permissions on NTFS in Windows - look here: https://technet.microsoft.com/en-us/library/cc754344(v=ws.11).aspx

**Comment by inge-j** [comment]
After moving the solution to a folder under my user profile, the PDB locks are no longer a problem, but now I get 

'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Service Fabric Tools\Microsoft.VisualStudio.Azure.Fabric.ServiceProject.targets(28,5): error : The project output folder is being used by a Service Fabric application. The fabric application didn't release the lock on the output folder within 00:02:00 minutes.' 

every time I try to deploy to the local cluster. Is this related to the PDB locking somehow or is it a different issue?

**Comment by sondreb** [comment]
I can verify we've had the same issue on multiple machines, and I have it on one of my machines.

The lock doesn't depend on what is actually running on the local SF instance, on my machine there are no applications deployed and I changed from 5 node to 1 node before upgrading VS 2017 to latest update.

Will this be fixed in the next release? Is it possible with a hotfix? This is holding up a lot of developers and a lot of time is wasted due to this bug.

**Comment by dbreshears** [comment]
The PDB locking issue should be resolved in the next release.    
@inge-j  -  this does seem like a different issue.   Are you on 1-node or 5-node cluster?     What is your cluster mode, 5-node or 1-node? Do you hit the same locking issue regardless.  What is your project "Application Debug mode" property set to?
@sondreb, are you talking about the PDB locking issue or are you hitting the same error as @inge-j?  If this is not the PDB locking issue we will need to see about getting a repro because the PDB locking issue is the only known locking  issue we have at the moment

**Comment by inge-j** [comment]
@dbreshears I have had the problem with both 1 and 5 node cluster setups. Also after resetting the cluster and even removing it through the Cluster Manager. I earlier had the PDB locking issue, but that was resolved by the permission workaround mentioned earlier in this thread.

**Comment by sondreb** [comment]
The PDB locks have been "easily" handled by one or three extra rebuilds, but now I'm having this error which is more serious and network service permission does not fix this:

"The fabric application didn't release the lock on the output folder within 00:02:00 minutes"

I get this for random 1 to 3 projects, if it happens on 6 it means VS simply hangs for a minimum of 6 minutes.

This is on Windows 10, VS 2017 with latest patches and latest SF SDK etc. The local cluster was reset when set to 1-node, no apps running on the local cluster, so this is not related.

**Comment by noocyte** [comment]
I'm getting the very same problem as @sondreb is having...

**Comment by mtucker2112** [comment]
We also have the same problem as @inge-j - except it only happens with 1-node clusters.  Our work-around is to switch to a 5-node cluster. Only then can we get past the 'The project output folder is being used by a Service Fabric application. The fabric application didn't release the lock on the output folder within 00:02:00 minutes.' error.

Our solutions are NOT under our user profile folder.  

In case it helps, here are the installed Azure\SF components:

![image](https://cloud.githubusercontent.com/assets/27865081/25396238/beb5f6c6-2998-11e7-9ab4-b7977d4966f3.png)

**Comment by dbreshears** [comment]
Ok.  So looks like we now have repro's on VS2015 and VS2017.     Can any of you please confirm if you are using Refresh Application Debug  mode [](https://blogs.msdn.microsoft.com/azureservicefabric/2017/04/17/speed-up-service-fabric-development-with-the-new-refresh-application-debug-mode-2/) or not?     What services make up your application/solution?   Any way to share a repro project or can someone help isolate what process is holding onto the output folder using procmon or some other utility

**Comment by dbreshears** [comment]
Here is the link to Refresh Application Debug mode info -> [https://blogs.msdn.microsoft.com/azureservicefabric/2017/04/17/speed-up-service-fabric-development-with-the-new-refresh-application-debug-mode-2/](url)

**Comment by fgauna12** [comment]
I'm getting the same problem as @sondreb. I do have my solution under %userprofile%

**Comment by inge-j** [comment]
Application debug mode is set to 'Remove Application'.

**Comment by Adebeer** [comment]
I've got the same issue - actually - i've had it since starting SF development using RC 0. I have to build the solution twice.

Anyway - thanks for the hint about Refresh Application Debug. I can confirm that it doesn't make a difference either way (I'm using 1 node cluster atm for development).

**Comment by Jakkob** [comment]
I'm also experiencing the issue that @inge-j, @sondreb, and @fgauna12 are describing.

The quick details:

- Application Debug Mode is set to 'Remove Application'. 
- Solution source is within my %userprofile%.
- Running latest versions of VS2017 and Service Fabric. 

Things I haven't tried yet:

- Switching to a 5-node local cluster. 
- Restricting the Network Service user's access to the project .pdb files. 

There's another detail with my manifestation of the issue that others have not yet mentioned: somewhat intermittent, excruciatingly slow build/clean times.

When attempting to clean or build, the following appears in the build output window after every the "Clean started..." message for every project:

```
6> Waiting for output folder cleanup...
6> Output folder cleanup has been completed.
```

The error is similar during a build as well but also includes a popup alert. I don't remember its text off the top of my head, but I'll update this post with more details as soon as I get into the office.

**Comment by Jakkob** [comment]
I backed up everything I could find. Please feel free to reach out if you need something.

**Comment by fgauna12** [comment]
Yesterday, I uninstalled the service fabric SDK and VS tooling. Then reinstalled everything and no issues so far.

**Comment by Jakkob** [comment]
@fgauna12 Yep. Uninstall/reinstall appears to have fixed it for me as well.

**Comment by dbreshears** [comment]
Thanks @Jakkob , @fgauna12,    Yep, we are investigating a synchronization issue with the project system and our WaitForApplicationCleanup task.    Trying to find a repro on our side and it seems that an event handle is not getting set as expected.

**Comment by Jakkob** [comment]
Thanks for working to save our sprints, @dbreshears and team!

**Comment by ravipal** [comment]
@jakkob When you say, reinstalling Service Fabric fixed the issue, did it fix the error "The fabric application didn't release the lock on the output folder within 00:02:00 minutes" or did it fix the slowness in build?

I am trying to repro this issue in my local environment and so far no repro. Those who hits the issue can you please share the following?
1. Number of services in the application. Is there any ASP .Net Core service in the application?
2. Build output when the error happens.
3. Local cluster state - is it running or stopped?

**Comment by Jakkob** [comment]
@ravipal Unfortunately, reinstalling SF only fixed the problem for about 15 minutes! After two or three test builds, it started failing again.

Regarding your questions:
1. The solution is a _bit_ over-sized currently. It contains the following:
    - 3 Service Fabric Applications.
    - 23 total services spread among the three apps. 20 stateless, 2 stateful, and 1 actor.
    - The solution as a whole weighs in at 66 total projects.
2. The console output in my post above shows what is being displayed, but I'd be happy to provide you with an example of the build output privately.
3. The problem manifests regardless of whether or not my cluster is currently running.

**Comment by ravipal** [comment]
@jakkob Thanks for the information. The console output didn't show error "The fabric application didn't release the lock on the output folder within 00:02:00 minutes". Is the issue that you mention is slowness in build caused by "Waiting for output folder cleanup..."?

If you are hitting the error "The fabric application didn't release the lock on the output folder within 00:02:00 minutes", please share the complete output to ravipal@microsoft.com

**Comment by Jakkob** [comment]
@ravipal Alrighty. Give me a few minutes and I'll collect those for you.

**Comment by ravipal** [comment]
@jakkob Also include the information whether the cluster is in running state or not. I suspect the slowness is caused by stopped 1 node cluster.

**Comment by Jakkob** [comment]
Okay @ravipal, it should be in your inbox.

I attached a zip file with four build output logs to the email, one for each of the following cases:
 
1. Minimal build output log level – Cluster running – 1 node    <– (This is how I typically run the solution.)
2. Detailed build output – Cluster running – 1 node
3. Detailed build output – Cluster stopped
4. Detailed output solution clean – Cluster stopped
 
***Case 4*** (the clean) does not mention the “...2:00 minutes...” error message, but it did take an very unusual amount (greater than five minutes) of time to complete. All the other logs do contain this error though.
                                    
Thanks again for your help!

**Comment by sondreb** [comment]
Finally got around to do some work to reproduce this problem, as mentioned I currently have it on my home computer. I attempted first to create a new empty service, both under user profile and C:\src. Both compiles and runs debug just fine.

When I open our source, which have a lot more services, I get this which hangs for the mentioned 2 minutes timeout:
![image](https://cloud.githubusercontent.com/assets/309938/25722663/31995c9a-3115-11e7-9c65-b7594634eeff.png)

VS 2017 - 15.1 (26403.7)
Windows 10 Insider - 16188
Fabric SDK 2.4.164 and 2.5.216 installed, and Tools for VS 2015 in both versions.

Unloading the cluster project within Visual Studio, and compilation of individual services works just fine, no issues at all, but as soon as I load the cluster project and recompile, it hangs.

**Comment by sondreb** [comment]
Some additional info, the service I created blank, I had it deployed and running locally. I choose to delete it, probably around the same time, or after I started a build in VS 2017 of the other project. It hang for a long time, and won't delete itself. Still waiting for it to delete, after 15 minutes. Not sure if it's related at all.

**Comment by ravipal** [comment]
Slow build or timeout during build can happen if the service fabric application has several services and the local cluster is 1-node cluster and it is not responsive. In 5.5 release, during build/clean, we check the cluster to see if the application is deployed. If the cluster is up and running and responding fine, then this check should take few milliseconds. but If the cluster is stopped or it is not responding, then this check takes some time and we do this for each service and it adds up and causes slow build or build timeout.  The next release (5.6) will have this fix.

**Comment by aL3891** [comment]
Great to hear i fix is coming, i've been seeing this lockup issue alot

**Comment by sondreb** [comment]
Latest Windows 10 Insider (16193) and latest Visual Studio 2017 update (15.2 26430.6) did it work me, appears to work fine now. Have not verified for a long time, but built a few times and F5 debugging works just fine. Running 5-node cluster locally.

So most likely there is a fix in the latest VS 2017 update that might fix the issue with "...2:00 minutes...", or I'm just lucky.

**Comment by ravipal** [comment]
@sondreb, this issue will not happen on 5-node cluster and it happens only on 1-node cluster and the cluster happens to be down/slow to respond. The fix is in 1.6 tooling which is not yet released in VS 2017. 1.6 tooling is available in VS 2017 preview though.

**Comment by aL3891** [comment]
Can confirm it works in the vs preview/1.6 tooling, i've not yet tried win vanilla vs2017.

**Comment by dbreshears** [comment]
Going to close the issue as we believe both issues have now been addressed by the 5.6 runtime and the 1.6 tooling.

**Comment by vdevappa** [comment]
The exact same locking problem happens with the latest SDK. I am getting it all the time. Latest VS 2017, Windows 10, latest SDK 2.6.204

**Comment by aL3891** [comment]
I have also observed this all though it is much more rare, atleast for me

**Comment by dbreshears** [comment]
@vdevappa.   Do you have VS 2017 Release (15.2) or Preview (15.3) channel?  Currently 1.5 version of the tooling is in Release and 1.6 tooling is in Preview channel.   @aL3891, I wonder if this could be related to one of the bugs in our 1.5 tooling that we addressed in  1.6  which would hang for several minutes checking application deployment status if the cluster was down or not responsive.

**Comment by aL3891** [comment]
Perhaps, i am running vs2017 and vs2017 preview side by side.. i do observe this issue in the preview version as well though. Maybe there is some issue with having the tooling side by side?

I've also felt it happening more often if it turns out there are build errors after the build actually complete, but that might just be coincidence.

**Comment by vdevappa** [comment]
I have VS 2017 release version.

**Comment by ravipal** [comment]
@vdevappa VS 2017 release version has 1.5 tooling, which doesn't have the fix.
@aL3891 side by side installation of vs and tooling should be fine. Can you please email the console output of the build to ravipal@microsoft.com that will help investigating the issue.

**Comment by mtucker2112** [comment]
We have this same issue with VS2015 and a 1-node cluster, using the 1.6.50508.2 tools.
@ravipal - is there a fix for VS2015?

**Comment by ravipal** [comment]
@mtucker2112, 1.6 version of the tooling that you have the fix. It seems that this bug happens in some other scenario. 

This error could happen if the cluster fails to respond to REST API call to check the application existence. Is your cluster running/healthy. Try restarting the cluster and see if this error happens again. How many services do you have in your application? Do you hit this error consistently? Can you please email the output of the build to ravipal@microsoft.com

**Comment by FredrikGoransson** [comment]
Why is this Issue closed? It is still very much alive and kicking even in the latest release of the tooling on VS2017.

**Comment by leikong** [comment]
The issue was closed after the offending was removed, this is probably a new issue, please provide more details to help us investigate, thanks.
