### ISSUE TITLE
Service Fabric Reverse Proxy - HTTP 500 0xd000003b 

### ISSUE THREAD

**Issue by stupiduglyfool** [Azure/service-fabric-issues#38]
I have followed the documentation as described here: https://azure.microsoft.com/en-us/documentation/articles/service-fabric-reverseproxy/

I additionally followed the section for setting up a SSL certificate.

Please note, the only deviation I've made whilst following that documentation, is to change the port I want the reverse proxy to listen on, from the documented 19008, to 443.

I have published stateless fabric service, it provides a katana webapi service.. listening on for example https://+:443/Opentree/Identity 

My fabric app url is fabric:/Opentree.Identity.Frontend/Service

If I try access this via https://someuri/Opentree.Identity.Frontend/Service I get a http 500 0xd000003b response

I RDP to the nodes in question, and the event viewer, under the service fabric section, I see "Creation of kNetworkEndpoint for uri https://IPAddress:443/Opentree/Identity/ failed with 0xd000003b"

**Comment by vaishnavk** [comment]
Can you try accessing the endpoint from a VM in the cluster where the service is running? This will help  isolate the issue.

**Comment by stupiduglyfool** [comment]
From external:

https://someuri/Opentree/Identity/ works
https://someuri/Opentree.Identity.Frontend/Service doesn't work

From an internal vm

https://localhost/Opentree/Identity/ works
https://localhost/Opentree.Identity.Frontend/Service doesn't work

Both internal/external accessing the proxy uri, I get 500 - 0xd000003b reported in chrome. And the same event viewer message I reported earlier is logged.

**Comment by vaishnavk** [comment]
Could this be service issue? Have you tried debugging this locally on a dev machine to ensure your service is working fine?

**Comment by stupiduglyfool** [comment]
The service itself is working fine locally, it also works fine in azure service fabric, it just doesn't work via the reverse proxy.

**Comment by chcaru** [comment]
@stupiduglyfool any update on this problem?

**Comment by stupiduglyfool** [comment]
I've had no luck resolving the problem yet

**Comment by Nosmadas** [comment]
Experiencing the same issue here.

**Comment by chcaru** [comment]
Are both of you using Guest Executables? It seems that the reverse proxy doesn't work with these OTB.. Create a simple OWIN Stateless WebAPI service from your dev box, then try:

http://localhost:19081/{appName}/{serviceName}/{pathSuffix}

It worked for me despite the previous issue.

(btw the 19081 is from the cluster manifest as seen through the fabric explorer)

**Comment by Nosmadas** [comment]
Using Kestrel with Https enabled and the reverse proxy bound to 443. Just tried writing a simple example using Kestrel without enabling https and it seemed to work fine.

**Comment by msfussell** [comment]
You can make the reverse proxy work with guest executables, you just need to ensure that you provided the scheme in the endpoint registration. Just updating the docs to describe this, but below is an example and a description. Note the UriScheme. So for example if you have a Node.js app that you want to use on a specific port you need to provide this. You can see if this works by looking at the endpoint address that is register with SF explorer. e.g. You should see for the example below http://localhost:3000

<Endpoints>
   <Endpoint Name="NodeAppTypeEndpoint" Protocol="http" Port="3000" UriScheme="http" PathSuffix="" />
</Endpoints>

```
The `Endpoint` element specifies the endpoints that the application can listen on. In this example, the Node.js application listens on port 3000. Service Fabric will also publish this endpoint to Service Fabric Naming service so other services can discover the endpoint address to this service. The published endpoint address is of the form "UriScheme://IPAddressOrFQDN:Port/PathSuffix". UriScheme and PathSuffix are optional attributes. IPAddressOrFQDN is the IPAddress or Fully Qualified Domain Name of the node this executable gets placed on.

**Comment by stupiduglyfool** [comment]
I presume you mean the endpoint element in ServiceManifest.xml?

I tried to add UriScheme and PathSuffix to this file, I can no longer deploy, Visual Studio reports that there is an error in the xml document.

`<Endpoints>      
      <Endpoint Name="ServiceEndpoint" Type="Input" UriScheme="https" PathSuffix="Opentree/Identity"  Protocol="https" Port="443" CertificateRef="DaveClusterCert"  />
    </Endpoints>
  </Resources>`

`------ Deploy started: Project: Opentree.Identity.Frontend.ServiceFabric.Deployment, Configuration: Debug x64 ------

There is an error in XML document (38, 53).`

38:53 corresponds to the UriScheme attribute.

**Comment by chcaru** [comment]
@stupiduglyfool I can confirm this one two separate machines, running the latest available SDK v2.2.207.9590

It seems there is some validation failing other than through the xml schema.

**Comment by msfussell** [comment]
This is a bug in the VS tool for validating the schema. We will get this fixed in the v2.3 release. To work around this for now you will have to use PowerShell commands for deploying the app.

**Comment by stupiduglyfool** [comment]
I have finally got around to working with this again, after implementing UriScheme="https" I can now deploy from Visual Studio.

However it does not fix the problem, I still get exactly the same error.

I am trying to host a https katana service on service fabric with reverse proxy. 

In the documentation it states:

"SSL termination occurs at the reverse proxy. Requests that are forwarded by the reverse proxy to services in the cluster are over http".

Does this mean it is actually impossible to have SSL services behind the reverse proxy?

**Comment by VipulM-MSFT** [comment]
Reverse proxy does not support HTTPS today. The support for it will be added in the future releases, however we do not have any timeline or ETA at this time.

The endpoint schema has evolved over the years and fields are used for different scenarios. Therefore it can be come confusing in the cases where they do not apply we have a enhancement planned to clean up the endpoint schema.

**Comment by stupiduglyfool** [comment]
There was a similar issue reported here https://github.com/Azure/service-fabric-issues/issues/90 

I had success getting my reverse proxy configured with https after following the guidance in the link provided:

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy-configure-secure-communication
