### ISSUE TITLE
`fabric:/System/RepairManagerService` not running after config upgrade for 6.0.211.9494 cluster

### ISSUE THREAD

**Issue by Mardoxx** [Azure/service-fabric-issues#526]
Following [this](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-patch-orchestration-application#prerequisites) for on prem.

My cluster is up to date with new config, i.e. incrementing config version and including
```json
    "AddonFeatures": [ 
        "RepairManager"
    ],
```
 but `fabric:/System/RepairManagerService` is not running.

There's also a typo and formatting errors in the docs which I've fixed https://github.com/MicrosoftDocs/azure-docs/pull/3420

**Comment by raunakpandya** [comment]
What version of cluster is this and what is the API version you are passing in the json?

**Comment by Mardoxx** [comment]
Cluster version: 6.0.211.9494
ApiVersion: 08-2017

**Comment by raunakpandya** [comment]
Can you share the output of Get-ServiceFabricClusterManifest after connecting to the cluster?

**Comment by Mardoxx** [comment]
```xml
<ClusterManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="WRP_Generated_ClusterManifest" Version="3" Description="This is a generated file. Do not modify." xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <NodeTypes>
    <NodeType Name="NodeType0">
      <Endpoints>
        <ClientConnectionEndpoint Port="19000" />
        <LeaseDriverEndpoint Port="19002" />
        <ClusterConnectionEndpoint Port="19001" />
        <HttpGatewayEndpoint Port="19080" Protocol="https" />
        <HttpApplicationGatewayEndpoint Port="19081" Protocol="https" />
        <ServiceConnectionEndpoint Port="19003" />
        <ApplicationEndpoints StartPort="20001" EndPort="20031" />
      </Endpoints>
      <Certificates>
        <ClusterCertificate X509FindValue="xxxxxxxxxx" Name="Certificate" />
        <ServerCertificate X509FindValue="xxxxxxxxxx" Name="Certificate" />
        <ClientCertificate X509FindValue="xxxxxxxxxx" Name="Certificate" />
      </Certificates>
      <PlacementProperties>
        <Property Name="NodeTypeName" Value="NodeType0" />
      </PlacementProperties>
    </NodeType>
  </NodeTypes>
  <Infrastructure>
    <WindowsServer>
      <NodeList>
        <Node NodeName="vm0" IPAddressOrFQDN="10.0.0.10" IsSeedNode="true" NodeTypeRef="NodeType0" FaultDomain="fd:/dc1/r0" UpgradeDomain="UD0" />
        <Node NodeName="vm1" IPAddressOrFQDN="10.0.0.11" IsSeedNode="true" NodeTypeRef="NodeType0" FaultDomain="fd:/dc1/r1" UpgradeDomain="UD1" />
        <Node NodeName="vm2" IPAddressOrFQDN="10.0.0.12" IsSeedNode="true" NodeTypeRef="NodeType0" FaultDomain="fd:/dc1/r2" UpgradeDomain="UD2" />
      </NodeList>
    </WindowsServer>
  </Infrastructure>
  <FabricSettings>
    <Section Name="ApplicationGateway/Http">
      <Parameter Name="GatewayAuthCredentialType" Value="X509" />
      <Parameter Name="GatewayX509CertificateFindType" Value="FindByThumbprint" />
      <Parameter Name="GatewayX509CertificateFindValue" Value="xxxxxxxxxx" />
      <Parameter Name="GatewayX509CertificateStoreName" Value="My" />
      <Parameter Name="IsEnabled" Value="true" />
    </Section>
    <Section Name="ClusterManager">
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==NodeType0" />
      <Parameter Name="TargetReplicaSetSize" Value="3" />
    </Section>
    <Section Name="Diagnostics">
      <Parameter Name="ClusterId" Value="32539aa4-59ea-46c8-824b-2f0f14397878" />
      <Parameter Name="ConsumerInstances" Value="FileShareWinFabEtw, FileShareWinFabCrashDump, FileShareWinFabPerfCtr" />
      <Parameter Name="EnableTelemetry" Value="False" />
      <Parameter Name="MaxDiskQuotaInMB" Value="5120" />
      <Parameter Name="ProducerInstances" Value="WinFabEtlFile, WinFabCrashDump, WinFabPerfCtrFolder" />
    </Section>
    <Section Name="FailoverManager">
      <Parameter Name="ExpectedClusterSize" Value="3" />
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==NodeType0" />
      <Parameter Name="TargetReplicaSetSize" Value="3" />
    </Section>
    <Section Name="FaultAnalysisService">
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==NodeType0" />
      <Parameter Name="TargetReplicaSetSize" Value="3" />
    </Section>
    <Section Name="Federation">
      <Parameter Name="NodeIdGeneratorVersion" Value="V4" />
    </Section>
    <Section Name="FileShareWinFabCrashDump">
      <Parameter Name="ConsumerType" Value="FileShareFolderUploader" />
      <Parameter Name="DataDeletionAgeInDays" Value="7" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerInstance" Value="WinFabCrashDump" />
      <Parameter Name="StoreConnectionString" Value="c:\ProgramData\SF\DiagnosticsStore\fabricdumps-32539aa4-59ea-46c8-824b-2f0f14397878" />
    </Section>
    <Section Name="FileShareWinFabEtw">
      <Parameter Name="ConsumerType" Value="FileShareEtwCsvUploader" />
      <Parameter Name="DataDeletionAgeInDays" Value="7" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerInstance" Value="WinFabEtlFile" />
      <Parameter Name="StoreConnectionString" Value="c:\ProgramData\SF\DiagnosticsStore\fabriclogs-32539aa4-59ea-46c8-824b-2f0f14397878" />
    </Section>
    <Section Name="FileShareWinFabPerfCtr">
      <Parameter Name="ConsumerType" Value="FileShareFolderUploader" />
      <Parameter Name="DataDeletionAgeInDays" Value="7" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerInstance" Value="WinFabPerfCtrFolder" />
      <Parameter Name="StoreConnectionString" Value="c:\ProgramData\SF\DiagnosticsStore\fabricperf-32539aa4-59ea-46c8-824b-2f0f14397878" />
    </Section>
    <Section Name="FileStoreService">
      <Parameter Name="AnonymousAccessEnabled" Value="false" />
      <Parameter Name="PrimaryAccountNTLMPasswordSecret" Value="46f224dc-fa0e-441d-ab13-fe446476baad" />
      <Parameter Name="PrimaryAccountNTLMX509StoreLocation" Value="LocalMachine" />
      <Parameter Name="PrimaryAccountNTLMX509StoreName" Value="My" />
      <Parameter Name="PrimaryAccountNTLMX509Thumbprint" Value="xxxxxxxxxx" />
      <Parameter Name="PrimaryAccountType" Value="LocalUser" />
      <Parameter Name="SecondaryAccountNTLMPasswordSecret" Value="f8d0deee-51fe-4e41-9964-e3b2a610d875" />
      <Parameter Name="SecondaryAccountNTLMX509StoreLocation" Value="LocalMachine" />
      <Parameter Name="SecondaryAccountNTLMX509StoreName" Value="My" />
      <Parameter Name="SecondaryAccountNTLMX509Thumbprint" Value="xxxxxxxxxx" />
      <Parameter Name="SecondaryAccountType" Value="LocalUser" />
    </Section>
    <Section Name="Hosting">
      <Parameter Name="EndpointProviderEnabled" Value="true" />
      <Parameter Name="FirewallPolicyEnabled" Value="true" />
      <Parameter Name="RunAsPolicyEnabled" Value="true" />
    </Section>
    <Section Name="HttpGateway">
      <Parameter Name="IsEnabled" Value="true" />
    </Section>
    <Section Name="ImageStoreService">
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==NodeType0" />
      <Parameter Name="TargetReplicaSetSize" Value="3" />
    </Section>
    <Section Name="Management">
      <Parameter Name="ImageStoreConnectionString" Value="fabric:ImageStore" />
    </Section>
    <Section Name="NamingService">
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==NodeType0" />
      <Parameter Name="TargetReplicaSetSize" Value="3" />
    </Section>
    <Section Name="ReconfigurationAgent">
      <Parameter Name="IsDeactivationInfoEnabled" Value="true" />
    </Section>
    <Section Name="Security">
      <Parameter Name="AdminClientCertThumbprints" Value="xxxxxxxxxx,xxxxxxxxxx,xxxxxxxxxx" />
      <Parameter Name="AllowDefaultClient" Value="False" />
      <Parameter Name="ClientCertThumbprints" Value="xxxxxxxxxx,xxxxxxxxxx" />
      <Parameter Name="ClientRoleEnabled" Value="true" />
      <Parameter Name="ClusterCertThumbprints" Value="xxxxxxxxxx" />
      <Parameter Name="ClusterCredentialType" Value="X509" />
      <Parameter Name="DisableFirewallRuleForDomainProfile" Value="true" />
      <Parameter Name="DisableFirewallRuleForPrivateProfile" Value="true" />
      <Parameter Name="DisableFirewallRuleForPublicProfile" Value="true" />
      <Parameter Name="IgnoreCrlOfflineError" Value="true" />
      <Parameter Name="ServerAuthCredentialType" Value="X509" />
      <Parameter Name="ServerCertThumbprints" Value="xxxxxxxxxx" />
    </Section>
    <Section Name="Setup">
      <Parameter Name="FabricDataRoot" Value="C:\ProgramData\SF" />
      <Parameter Name="FabricLogRoot" Value="C:\ProgramData\SF\Log" />
    </Section>
    <Section Name="Trace/Etw">
      <Parameter Name="Level" Value="4" />
    </Section>
    <Section Name="UpgradeOrchestrationService">
      <Parameter Name="AutoupgradeEnabled" Value="True" />
      <Parameter Name="ClusterId" Value="32539aa4-59ea-46c8-824b-2f0f14397878" />
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==NodeType0" />
      <Parameter Name="TargetReplicaSetSize" Value="3" />
    </Section>
    <Section Name="WinFabCrashDump">
      <Parameter Name="DataDeletionAgeInDays" Value="7" />
      <Parameter Name="FolderType" Value="WindowsFabricCrashDumps" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerType" Value="FolderProducer" />
    </Section>
    <Section Name="WinFabEtlFile">
      <Parameter Name="DataDeletionAgeInDays" Value="7" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerType" Value="EtlFileProducer" />
    </Section>
    <Section Name="WinFabPerfCtrFolder">
      <Parameter Name="DataDeletionAgeInDays" Value="7" />
      <Parameter Name="FolderType" Value="WindowsFabricPerformanceCounters" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerType" Value="FolderProducer" />
    </Section>
  </FabricSettings>
</ClusterManifest>
```

**Comment by raunakpandya** [comment]
Doesn't seem like your config upgrade went through.. Can you give it a try once more?

**Comment by Mardoxx** [comment]
Sure!

It fails now :(

```powershell
PS C:\> Get-ServiceFabricClusterConfiguration | Out-File config.json
# edit ClusterConfigurationVersion to 1.0.5
PS C:\> Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath .\config.json
PS C:\> Get-ServiceFabricClusterConfigurationUpgradeStatus

            UpgradeState ProgressStatus ConfigVersion Details
            ------------ -------------- ------------- -------
RollingForwardInProgress              4 1.0.4


PS C:\> Get-ServiceFabricClusterConfigurationUpgradeStatus

UpgradeState ProgressStatus ConfigVersion Details
------------ -------------- ------------- -------
      Failed              4 1.0.4


PS C:\>
```

**Comment by Mardoxx** [comment]
Upon removing `RepairManager` from `AddonFeatures` I am met with this:
```powershell
Start-ServiceFabricClusterConfigurationUpgrade : System.Runtime.InteropServices.COMException (-2147017627)
ValidationException: Removing Repair Manager Service is not supported.
```

**Comment by Mardoxx** [comment]
Event viewer for (failed) upgrade is as follows:

```xml
Log Name:      Microsoft-ServiceFabric/Admin
Source:        Microsoft-ServiceFabric
Date:          12/10/2017 11:29:12
Event ID:      59648
Task Category: ImageBuilder
Level:         Error
Keywords:      Default
User:          NETWORK SERVICE
Computer:      VM1
Description:
The upgrade is not allowed due to exception System.ArgumentException: The upgrade policy is not allowed
   at System.Fabric.Management.WindowsFabricValidator.FabricSettingsValidator.WriteError(String format, Object[] args)
   at System.Fabric.Management.WindowsFabricValidator.FabricSettingsValidator.CompareSettings(ClusterManifestType newClusterManifest, String nodeTypeNameFilter)
   at System.Fabric.Management.ImageBuilder.FabricUpgradeOperation.UpgradeFabric(String currentFabricVersion, String targetFabricVersion, String configurationCsvFilePath, TimeSpan timeout, Boolean& isConfigOnly). CurrentFabricVersion:6.0.211.9494:3, TargetFabricVersion:6.0.211.9494:4
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-ServiceFabric" Guid="{CBD93BC2-71E5-4566-B3A7-595D8EECA6E8}" />
    <EventID>59648</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>233</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000001</Keywords>
    <TimeCreated SystemTime="2017-10-12T10:29:12.918767700Z" />
    <EventRecordID>46821</EventRecordID>
    <Correlation />
    <Execution ProcessID="7968" ThreadID="17976" />
    <Channel>Microsoft-ServiceFabric/Admin</Channel>
    <Computer>VM1</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="id">
    </Data>
    <Data Name="type">FabricUpgradeOperation</Data>
    <Data Name="message">The upgrade is not allowed due to exception System.ArgumentException: The upgrade policy is not allowed
   at System.Fabric.Management.WindowsFabricValidator.FabricSettingsValidator.WriteError(String format, Object[] args)
   at System.Fabric.Management.WindowsFabricValidator.FabricSettingsValidator.CompareSettings(ClusterManifestType newClusterManifest, String nodeTypeNameFilter)
   at System.Fabric.Management.ImageBuilder.FabricUpgradeOperation.UpgradeFabric(String currentFabricVersion, String targetFabricVersion, String configurationCsvFilePath, TimeSpan timeout, Boolean&amp; isConfigOnly). CurrentFabricVersion:6.0.211.9494:3, TargetFabricVersion:6.0.211.9494:4</Data>
  </EventData>
</Event>
```

**Comment by raunakpandya** [comment]
Yes, removing RepairManager once added is not allowed. And most likely the above failure is because of the same. We need to understand why the first upgrade where you enabled RepairManager didn't go through. To summarize your steps correctly, you added the RepairManager addOnFeatures section and incremented the config version and triggered and upgrade. Did that upgrade complete successfully or it rolled back? We will have to take a look at the logs here. Let me get back with steps on how to share the same.

**Comment by Mardoxx** [comment]
It appeared to succeed with cluster config version being reflected as 1.0.4 now, when previously (before trying to enable RepairManager) it was 1.0.3.

**Comment by Mardoxx** [comment]
I downgraded to `5.7.221.9494` Re-triggered config upgrade, manifest now contains

```xml
    <Section Name="RepairManager">
      <Parameter Name="EnableHealthChecks" Value="True" />
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="TargetReplicaSetSize" Value="3" />
    </Section>
```

**Comment by Mardoxx** [comment]
Are the service fabric application cabinet files identical on Azure as the ones for on prem?

If so, it would seem that installing RepairManager on an existing cluster is broken.

----
I'm currently being blocked by 6.0 not being released for onprem clusters, so created an azure one, exported the cab, and updated my cluster using this cab, and everything worked fine.. Until it came to installing RepairManager. Hope this helps. Thanks a lot for your support!

**Comment by raunakpandya** [comment]
What do you mean by exported the cab? The earlier issue was on prem or Azure?

Thanks,
Raunak Pandya
________________________________

**Comment by Mardoxx** [comment]
I needed 6.0 on my on prem cluster, but you haven't released it yet. I gathered that as you use same runtimes on Azure as on prem I could just copy the 6.0 SF code package from an Azure SF VM and install it on my own.

I copied `WindowsFabric.6.0.211.9494.cab` from ImageStore on my Azure cluster and performed an upgrade as outlined [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-upgrade-windows-server#control-the-service-fabric-version-that-runs-on-your-cluster). It worked fine.

Earlier issue was with on prem. But I would imaigne the same issue would happen whereby someone has an existing 5.x cluster without RepairManager, upgrades to 6.0, then tries to install RepairManager.

**Comment by Mardoxx** [comment]
In summary, to reproduce:

1. Create 5.7 cluster without `RepairManager`
2. Upgrade to 6.0
3. Perform cluster config upgrade with `"RepairManager"` appended to `"AddonFeatures"` array
4. `RepairManager` will not be installed. even though cluster config says it should be. (Check CLusterManifest for missing `RepairManager` entries)

Remediation for this is:
1. Downgrade to 5.7 - ensure this can succeed either by setting appropriate upgrade policies (or remove any instances of applications which require 6.0 runtime)
2. Perform cluster config upgrade with `"RepairManager"` appended to `"AddonFeatures"` array
3. Re-upgrade to 6.0

**Comment by Liphi** [comment]
Hi Mardoxx, I can't seem to repro the issue. Could u provide the 2 cluster json config used in ur repro steps (the one creating the 5.7 cluster, and the one used to config upgrade after code upgrading to 6.0) ?

**Comment by Mardoxx** [comment]
Cluster configurations and application packages are in attachment [here](https://drive.google.com/file/d/0B_Js0b3pZXbLbHJ6ZVltZmtuWEE/view?usp=sharing).

In case it matters, my cluster version history is as follows:
5.5.216.0
5.6.220.9494
5.7.198.9494

The initial config.json was a modified 3-node secure cluster with reverse proxy enabled and secured with https cert.

I never installed 5.7.221.9494. I would assume this issue can be reproduced starting with 5.7.198.9494.

1. Setup a standalone cluster using SF 5.7.198.9494 and apply given cluster configuration below (v1.0.3)
2. Upgrade using 6.0.211.9494 cab lifted from an Azure SF node running 6.0.211.9494 following these steps https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-upgrade-windows-server
3. Attempt to upgrade cluster to new configuration (v1.0.4)
4. Get-ServiceFabricClusterConfiguration should reflect 1.0.4, but cluster manifest will not have RepairService definitions.


```json
{
  "Properties": {
    "Security": {
      "$id": "1",
      "CertificateInformation": {
        "$id": "2",
        "ClusterCertificate": {
          "Thumbprint": "xxxxxxxxxxxx",
          "X509StoreName": "My"
        },
        "ServerCertificate": {
          "Thumbprint": "xxxxxxxxxxxx",
          "X509StoreName": "My"
        },
        "ReverseProxyCertificate": {
          "Thumbprint": "yyyyyyyyyyyy",
          "X509StoreName": "My"
        },
        "ClientCertificateThumbprints": [
          {
            "IsAdmin": true,
            "CertificateThumbprint": "zzzzzzzzzzzz"
          },
          {
            "IsAdmin": true,
            "CertificateThumbprint": "aaaaaaaaaaaa"
          },
          {
            "IsAdmin": false,
            "CertificateThumbprint": "aaaaaaaaaaaa"
          }
        ]
      },
      "WindowsIdentities": {
        "$id": "3"
      },
      "ClusterCredentialType": "X509",
      "ServerCredentialType": "X509"
    },
    "NodeTypes": [
      {
        "Name": "NodeType0",
        "ClientConnectionEndpointPort": 19000,
        "HttpGatewayEndpointPort": 19080,
        "ReverseProxyEndpointPort": 19081,
        "LeaseDriverEndpointPort": 19002,
        "ClusterConnectionEndpointPort": 19001,
        "ServiceConnectionEndpointPort": 19003,
        "ApplicationPorts": {
          "StartPort": 20001,
          "EndPort": 20031
        },
        "IsPrimary": true
      }
    ],
    "AddonFeatures": [
    ],
    "FabricSettings": [
      {
        "Name": "Setup",
        "Parameters": [
          {
            "Name": "FabricDataRoot",
            "Value": "C:\\ProgramData\\SF"
          },
          {
            "Name": "FabricLogRoot",
            "Value": "C:\\ProgramData\\SF\\Log"
          }
        ]
      }
    ],
    "EnableTelemetry": false,
    "DiagnosticsStore": {
      "StoreType": "FileShare",
      "DataDeletionAgeInDays": 7,
      "Connectionstring": "c:\\ProgramData\\SF\\DiagnosticsStore",
      "IsEncrypted": false
    },
    "FabricClusterAutoupgradeEnabled": true
  },
  "Nodes": [
    {
      "NodeName": "vm2",
      "NodeTypeRef": "NodeType0",
      "IPAddress": "10.0.0.12",
      "FaultDomain": "fd:/dc1/r2",
      "UpgradeDomain": "UD2"
    },
    {
      "NodeName": "vm1",
      "NodeTypeRef": "NodeType0",
      "IPAddress": "10.0.0.11",
      "FaultDomain": "fd:/dc1/r1",
      "UpgradeDomain": "UD1"
    },
    {
      "NodeName": "vm0",
      "NodeTypeRef": "NodeType0",
      "IPAddress": "10.0.0.10",
      "FaultDomain": "fd:/dc1/r0",
      "UpgradeDomain": "UD0"
    }
  ],
  "ApiVersion": "05-2017",
  "Name": "TestCluster",
  "ClusterConfigurationVersion": "1.0.3"
}
```

1.0.4
```json
{
  "Properties": {
    "Security": {
      "$id": "1",
      "CertificateInformation": {
        "$id": "2",
        "ClusterCertificate": {
          "Thumbprint": "xxxxxxxxxxxx",
          "X509StoreName": "My"
        },
        "ServerCertificate": {
          "Thumbprint": "xxxxxxxxxxxx",
          "X509StoreName": "My"
        },
        "ReverseProxyCertificate": {
          "Thumbprint": "yyyyyyyyyyyy",
          "X509StoreName": "My"
        },
        "ClientCertificateThumbprints": [
          {
            "IsAdmin": true,
            "CertificateThumbprint": "zzzzzzzzzzzz"
          },
          {
            "IsAdmin": true,
            "CertificateThumbprint": "aaaaaaaaaaaa"
          },
          {
            "IsAdmin": false,
            "CertificateThumbprint": "aaaaaaaaaaaa"
          }
        ]
      },
      "WindowsIdentities": {
        "$id": "3"
      },
      "ClusterCredentialType": "X509",
      "ServerCredentialType": "X509"
    },
    "NodeTypes": [
      {
        "Name": "NodeType0",
        "ClientConnectionEndpointPort": 19000,
        "HttpGatewayEndpointPort": 19080,
        "ReverseProxyEndpointPort": 19081,
        "LeaseDriverEndpointPort": 19002,
        "ClusterConnectionEndpointPort": 19001,
        "ServiceConnectionEndpointPort": 19003,
        "ApplicationPorts": {
          "StartPort": 20001,
          "EndPort": 20031
        },
        "IsPrimary": true
      }
    ],
    "AddonFeatures": [
        "RepairManager"
    ],
    "FabricSettings": [
      {
        "Name": "Setup",
        "Parameters": [
          {
            "Name": "FabricDataRoot",
            "Value": "C:\\ProgramData\\SF"
          },
          {
            "Name": "FabricLogRoot",
            "Value": "C:\\ProgramData\\SF\\Log"
          }
        ]
      }
    ],
    "EnableTelemetry": false,
    "DiagnosticsStore": {
      "StoreType": "FileShare",
      "DataDeletionAgeInDays": 7,
      "Connectionstring": "c:\\ProgramData\\SF\\DiagnosticsStore",
      "IsEncrypted": false
    },
    "FabricClusterAutoupgradeEnabled": true
  },
  "Nodes": [
    {
      "NodeName": "vm2",
      "NodeTypeRef": "NodeType0",
      "IPAddress": "10.0.0.12",
      "FaultDomain": "fd:/dc1/r2",
      "UpgradeDomain": "UD2"
    },
    {
      "NodeName": "vm1",
      "NodeTypeRef": "NodeType0",
      "IPAddress": "10.0.0.11",
      "FaultDomain": "fd:/dc1/r1",
      "UpgradeDomain": "UD1"
    },
    {
      "NodeName": "vm0",
      "NodeTypeRef": "NodeType0",
      "IPAddress": "10.0.0.10",
      "FaultDomain": "fd:/dc1/r0",
      "UpgradeDomain": "UD0"
    }
  ],
  "ApiVersion": "08-2017",
  "Name": "TestCluster",
  "ClusterConfigurationVersion": "1.0.4"
}
```

**Comment by Liphi** [comment]
Thx for detailed info. The issue can be repro-ed now. It is a regression introduced in 5.7 CU4 (5.7.221) and 6.0. I will fix it. And your work-around of downgrading->configUpgrade->codeUpgrade is expected.

**Comment by Mardoxx** [comment]
Absolutely my pleasure! 😄

On 12 Oct 2017 11:18 pm, "Liphi" <notifications@github.com> wrote:

Thx for detailed info. The issue can be repro-ed now. It is a regression
introduced in 5.7 CU4 (5.7.221) and 6.0. I will fix it. And your
work-around of downgrading->configUpgrade->codeUpgrade is expected.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/service-fabric-issues/issues/526#issuecomment-336292042>,
or mute the thread

**Comment by ThiemeNL** [comment]
Hi is there on update on when the fix is coming? I cannot use the workaround because my applications are depended on runtime 6. Downgrading will fail.

**Comment by novino** [comment]
@Liphi could you help @ThiemeNL with a possible mitigation.

**Comment by Mardoxx** [comment]
Its been fixed in 6.0.219.9494.

**Comment by ThiemeNL** [comment]
Okay thanks, I didn't notice the 6.0.219.9494. I paused my work a couple of days ago (when there was no update available) because of this issue. I was running on 6.0.211.9494. So I will give it a retry.

**Comment by ThiemeNL** [comment]
I did the upgrade to 6.0.219.9494, but the repair manager is still not visible. We run SF in Azure westeurope.

![image](https://user-images.githubusercontent.com/5397828/32111063-af9c1a8e-bb39-11e7-87c2-2d52e6451f39.png)

The repair manager does appears in the manifest:

```xml
<ClusterManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="WRP_Generated_ClusterManifest" Version="12" Description="This is a generated file. Do not modify." xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <NodeTypes>
    <NodeType Name="backend">
      <Endpoints>
        <ClientConnectionEndpoint Port="19000" />
        <LeaseDriverEndpoint Port="1026" />
        <ClusterConnectionEndpoint Port="1025" />
        <HttpGatewayEndpoint Port="19080" Protocol="https" />
        <ServiceConnectionEndpoint Port="1027" />
        <ApplicationEndpoints StartPort="20000" EndPort="30000" />
        <EphemeralEndpoints StartPort="49152" EndPort="65534" />
      </Endpoints>
      <Certificates>
        <ClusterCertificate X509FindValue="AA" Name="Certificate" />
        <ServerCertificate X509FindValue="AA" Name="Certificate" />
        <ClientCertificate X509FindValue="AA" Name="Certificate" />
      </Certificates>
      <PlacementProperties>
        <Property Name="NodeTypeName" Value="backend" />
      </PlacementProperties>
    </NodeType>
  </NodeTypes>
  <Infrastructure>
    <PaaS>
      <Roles>
        <Role RoleName="backend" NodeTypeRef="backend" RoleNodeCount="5" />
      </Roles>
      <Votes>
        <Vote NodeName="_backend_0" IPAddressOrFQDN="10.0.0.4" Port="1025" />
        <Vote NodeName="_backend_1" IPAddressOrFQDN="10.0.0.5" Port="1025" />
        <Vote NodeName="_backend_2" IPAddressOrFQDN="10.0.0.6" Port="1025" />
        <Vote NodeName="_backend_3" IPAddressOrFQDN="10.0.0.7" Port="1025" />
        <Vote NodeName="_backend_4" IPAddressOrFQDN="10.0.0.8" Port="1025" />
      </Votes>
    </PaaS>
  </Infrastructure>
  <FabricSettings>
    <Section Name="AzureBlobServiceFabricCrashDump">
      <Parameter Name="ConsumerType" Value="AzureBlobFolderUploader" />
      <Parameter Name="ContainerName" Value="XXX" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerInstance" Value="ServiceFabricCrashDump" />
      <Parameter Name="StoreConnectionString" Value="XX" />
    </Section>
    <Section Name="AzureBlobServiceFabricEtw">
      <Parameter Name="ConsumerType" Value="AzureBlobEtwCsvUploader" />
      <Parameter Name="ContainerName" Value="XX" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerInstance" Value="ServiceFabricEtlFile" />
      <Parameter Name="StoreConnectionString" Value="XX" />
    </Section>
    <Section Name="AzureBlobServiceFabricPerfCounter">
      <Parameter Name="ConsumerType" Value="AzureBlobFolderUploader" />
      <Parameter Name="ContainerName" Value="XX" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerInstance" Value="ServiceFabricPerfCounter" />
      <Parameter Name="StoreConnectionString" Value="XX" />
    </Section>
    <Section Name="AzureTableServiceFabricEtwQueryable">
      <Parameter Name="ConsumerType" Value="AzureTableQueryableEventUploader" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerInstance" Value="ServiceFabricEtlFileQueryable" />
      <Parameter Name="StoreConnectionString" Value="XX" />
      <Parameter Name="TableNamePrefix" Value="XX" />
    </Section>
    <Section Name="ClusterManager">
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==backend" />
      <Parameter Name="TargetReplicaSetSize" Value="5" />
    </Section>
    <Section Name="Common">
      <Parameter Name="EnableEndpointV2" Value="true" />
    </Section>
    <Section Name="Diagnostics">
      <Parameter Name="ConsumerInstances" Value="AzureBlobServiceFabricEtw, AzureTableServiceFabricEtwQueryable, AzureBlobServiceFabricCrashDump, AzureBlobServiceFabricPerfCounter" />
      <Parameter Name="MaxDiskQuotaInMB" Value="5120" />
      <Parameter Name="ProducerInstances" Value="ServiceFabricEtlFile, ServiceFabricEtlFileQueryable, ServiceFabricCrashDump, ServiceFabricPerfCounter" />
    </Section>
    <Section Name="FailoverManager">
      <Parameter Name="ExpectedClusterSize" Value="5" />
      <Parameter Name="IsSingletonReplicaMoveAllowedDuringUpgrade" Value="True" />
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==backend" />
      <Parameter Name="TargetReplicaSetSize" Value="5" />
    </Section>
    <Section Name="FaultAnalysisService">
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==backend" />
      <Parameter Name="TargetReplicaSetSize" Value="5" />
    </Section>
    <Section Name="Federation">
      <Parameter Name="NodeIdGeneratorVersion" Value="V4" />
    </Section>
    <Section Name="FileStoreService">
      <Parameter Name="AnonymousAccessEnabled" Value="false" />
      <Parameter Name="PrimaryAccountNTLMPasswordSecret" Value="XX" />
      <Parameter Name="PrimaryAccountNTLMX509StoreLocation" Value="XX" />
      <Parameter Name="PrimaryAccountNTLMX509StoreName" Value="XX" />
      <Parameter Name="PrimaryAccountNTLMX509Thumbprint" Value="XX" />
      <Parameter Name="PrimaryAccountType" Value="XX" />
      <Parameter Name="SecondaryAccountNTLMPasswordSecret" Value="XX" />
      <Parameter Name="SecondaryAccountNTLMX509StoreLocation" Value="XX" />
      <Parameter Name="SecondaryAccountNTLMX509StoreName" Value="XX" />
      <Parameter Name="SecondaryAccountNTLMX509Thumbprint" Value="XX" />
      <Parameter Name="SecondaryAccountType" Value="XX" />
    </Section>
    <Section Name="Hosting">
      <Parameter Name="EndpointProviderEnabled" Value="true" />
      <Parameter Name="FirewallPolicyEnabled" Value="true" />
      <Parameter Name="RunAsPolicyEnabled" Value="true" />
    </Section>
    <Section Name="HttpGateway">
      <Parameter Name="IsEnabled" Value="true" />
    </Section>
    <Section Name="ImageStoreService">
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==backend" />
      <Parameter Name="TargetReplicaSetSize" Value="5" />
    </Section>
    <Section Name="Management">
      <Parameter Name="EnableDeploymentAtDataRoot" Value="true" />
      <Parameter Name="ImageStoreConnectionString" Value="fabric:ImageStore" />
    </Section>
    <Section Name="NamingService">
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==backend" />
      <Parameter Name="TargetReplicaSetSize" Value="5" />
    </Section>
    <Section Name="Paas">
      <Parameter Name="ClusterId" Value="XX" />
    </Section>
    <Section Name="ReconfigurationAgent">
      <Parameter Name="IsDeactivationInfoEnabled" Value="true" />
    </Section>
    <Section Name="RepairManager">
      <Parameter Name="EnableHealthChecks" Value="True" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==backend" />
    </Section>
    <Section Name="Security">
      <Parameter Name="AADClientApplication" Value="XX" />
      <Parameter Name="AADClusterApplication" Value="XX" />
      <Parameter Name="AADTenantId" Value="XX" />
      <Parameter Name="AdminClientCertThumbprints" Value="XX" />
      <Parameter Name="ClientAuthAllowedCommonNames" Value="westeurope.servicefabric.azure.com" />
      <Parameter Name="ClientCertThumbprints" Value="XX" />
      <Parameter Name="ClientRoleEnabled" Value="true" />
      <Parameter Name="ClusterCertThumbprints" Value="XX" />
      <Parameter Name="ClusterCredentialType" Value="X509" />
      <Parameter Name="ClusterProtectionLevel" Value="EncryptAndSign" />
      <Parameter Name="DisableFirewallRuleForDomainProfile" Value="false" />
      <Parameter Name="DisableFirewallRuleForPrivateProfile" Value="false" />
      <Parameter Name="DisableFirewallRuleForPublicProfile" Value="false" />
      <Parameter Name="IgnoreCrlOfflineError" Value="true" />
      <Parameter Name="ServerAuthCredentialType" Value="X509" />
      <Parameter Name="ServerCertThumbprints" Value="XX" />
      <Parameter Name="UseSecondaryIfNewer" Value="true" />
    </Section>
    <Section Name="ServiceFabricCrashDump">
      <Parameter Name="FolderType" Value="WindowsFabricCrashDumps" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerType" Value="FolderProducer" />
    </Section>
    <Section Name="ServiceFabricEtlFile">
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerType" Value="EtlFileProducer" />
    </Section>
    <Section Name="ServiceFabricEtlFileQueryable">
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerType" Value="EtlFileProducer" />
      <Parameter Name="WindowsFabricEtlType" Value="QueryEtl" />
    </Section>
    <Section Name="ServiceFabricPerfCounter">
      <Parameter Name="FolderType" Value="WindowsFabricPerformanceCounters" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerType" Value="FolderProducer" />
    </Section>
    <Section Name="Trace/Etw">
      <Parameter Name="Level" Value="4" />
    </Section>
    <Section Name="UpgradeService">
      <Parameter Name="BaseUrl" Value="https://westeurope.servicefabric.azure.com/runtime/clusters/" />
      <Parameter Name="CoordinatorType" Value="Paas" />
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==backend" />
      <Parameter Name="TargetReplicaSetSize" Value="5" />
      <Parameter Name="X509FindType" Value="FindByThumbprint" />
      <Parameter Name="X509FindValue" Value="XX" />
      <Parameter Name="X509StoreLocation" Value="LocalMachine" />
      <Parameter Name="X509StoreName" Value="My" />
    </Section>
  </FabricSettings>
</ClusterManifest>
```

And also in the template "Microsoft.ServiceFabric/clusters":
```json
{
  "type": "Microsoft.ServiceFabric/clusters",
  "location": "westeurope",
  "id": "XX",
  "name": "XX",
  "tags": {
    "resourceType": "Service Fabric",
    "clusterName": XX"
  },
  "etag": "W/\"636316379493319896\"",
  "properties": {
    "provisioningState": "Succeeded",
    "clusterId": "XX",
    "clusterCodeVersion": "6.0.219.9494",
    "clusterState": "Ready",
    "managementEndpoint": "https://xx:19080",
    "clusterEndpoint": "https://xx",
    "certificate": {
      "thumbprint": "xx",
      "x509StoreName": "My"
    },
    "clientCertificateThumbprints": [],
    "clientCertificateCommonNames": [],
    "fabricSettings": [
      {
        "name": "Security",
        "parameters": [
          {
            "name": "ClusterProtectionLevel",
            "value": "EncryptAndSign"
          }
        ]
      }
    ],
    "upgradeDescription": {
      "overrideUserUpgradePolicy": false,
      "forceRestart": false,
      "upgradeReplicaSetCheckTimeout": "10675199.02:48:05.4775807",
      "healthCheckWaitDuration": "00:05:00",
      "healthCheckStableDuration": "00:05:00",
      "healthCheckRetryTimeout": "00:45:00",
      "upgradeTimeout": "12:00:00",
      "upgradeDomainTimeout": "02:00:00",
      "healthPolicy": {
        "maxPercentUnhealthyNodes": 100,
        "maxPercentUnhealthyApplications": 100
      },
      "deltaHealthPolicy": {
        "maxPercentDeltaUnhealthyNodes": 0,
        "maxPercentUpgradeDomainDeltaUnhealthyNodes": 0,
        "maxPercentDeltaUnhealthyApplications": 0
      }
    },
    "diagnosticsStorageAccountConfig": {
      "storageAccountName": "xxx",
      "protectedAccountKeyName": "xxx",
      "blobEndpoint": "xxx",
      "queueEndpoint": "xxx",
      "tableEndpoint": "xxx"
    },
    "nodeTypes": [
      {
        "name": "backend",
        "clientConnectionEndpointPort": 19000,
        "httpGatewayEndpointPort": 19080,
        "applicationPorts": {
          "startPort": 20000,
          "endPort": 30000
        },
        "ephemeralPorts": {
          "startPort": 49152,
          "endPort": 65534
        },
        "isPrimary": true,
        "vmInstanceCount": 5,
        "durabilityLevel": "Bronze"
      }
    ],
    "vmImage": "Windows",
    "azureActiveDirectory": {
      "tenantId": "xxx",
      "clusterApplication": "xxx",
      "clientApplication": "xxx"
    },
    "reliabilityLevel": "Silver",
    "upgradeMode": "Manual",
    "availableClusterVersions": [
      {
        "codeVersion": "5.7.221.9494",
        "supportExpiryUtc": "2017-12-15T00:00:00",
        "environment": "Windows"
      },
      {
        "codeVersion": "6.0.211.9494",
        "supportExpiryUtc": "9999-12-31T23:59:59.9999999",
        "environment": "Windows"
      },
      {
        "codeVersion": "6.0.219.9494",
        "supportExpiryUtc": "9999-12-31T23:59:59.9999999",
        "environment": "Windows"
      }
    ],
    "addonFeatures": [
      "RepairManager"
    ]
  }
}
```

**Comment by Mardoxx** [comment]
```xml

<Section Name="RepairManager">
      <Parameter Name="EnableHealthChecks" Value="True" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==backend" />
    </Section>

```

Looks ok to me?

**Comment by Liphi** [comment]
Without XXXReplicaSetSize parameters, RepairManager doesn't come up.
@ThiemeNL  ur cluster is on Azure. The Azure fix has been coded but hasn't been deployed yet.

**Comment by ThiemeNL** [comment]
Hi @Liphi any update on the deployment? Can I try it again?

**Comment by Liphi** [comment]
@vaishnavk Could u confirm on the deployment schedule for the fix?

**Comment by ThiemeNL** [comment]
@vaishnavk can you please give an update?

**Comment by vaishnavk** [comment]
@ThiemeNL  The latest CU with the fix has been deployed to all public regions.

**Comment by ThiemeNL** [comment]
Hmm great, now the UpgradeService crashed...
And the the upgrade process keeps hanging for almost 24hours now:
![image](https://user-images.githubusercontent.com/5397828/33211597-9313fa66-d11f-11e7-9c2f-c20f80cb6cf9.png)

```
	Error event: SourceId='UpgradeService.Primary', Property='SFRPPoll'.
Exception encountered: System.Fabric.FabricException: The upgrade is not allowed due to exception System.ArgumentException: The upgrade policy is not allowed
   at System.Fabric.Management.WindowsFabricValidator.FabricSettingsValidator.CompareSettings(ClusterManifestType newClusterManifest, String nodeTypeNameFilter)
   at System.Fabric.Management.ImageBuilder.FabricUpgradeOperation.UpgradeFabric(String currentFabricVersion, String targetFabricVersion, String configurationCsvFilePath, TimeSpan timeout, Boolean& isConfigOnly). CurrentFabricVersion:6.0.219.9494:12, TargetFabricVersion:6.0.232.9494:17 ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071BE6
   at System.Fabric.Interop.NativeClient.IFabricClusterManagementClient10.EndUpgradeFabric(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.b__0(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.FabricClientWrapper.d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.FabricClientWrapper.d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.ClusterCoordinator.d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.ClusterCoordinator.d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.ClusterCoordinator.d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.ClusterCoordinator.d__17.MoveNext()
```

**Comment by Liphi** [comment]
U need to upgrade ur cluster runtime code version to the latest 6.0 CU version (6.0.232.9494).

**Comment by ThiemeNL** [comment]
Hi, I managed to add the RepairManager with help of Azure support. We found out that there still was an issue, but it is now fixed in 6.0 CU2. The resolution for me was: 

1.	You need to monitor your cluster to change the state back to ‘Ready’ from ‘UpdatingUserConfiguration’, and mostly this will happen during 12/7 after deploying the fix in westeurope region.
2.	Upgrade version to 6.0.232
3.	Remove the RM Service with an cluster upgrade (You wanted to remove the Addon setting for RM from Fabric setting )
4.	Add the RM Service , and after that you can find the Repair Manager Service. 

I think you can close the issue. Thanks.

**Comment by vaishnavk** [comment]
The issue has been fixed.
