### ISSUE TITLE
Services.Remoting.V1 in net47 vs net46 libraries (v3.0.472)

### ISSUE THREAD

**Issue by festivus** [Azure/service-fabric-issues#930]
Microsoft.ServiceFabric.Services.Remoting.V1 is not supported in net47.

Reproduce this:
Clone https://github.com/festivus/ServiceProxySample
Open the csproj files
Replace <TargetFrameworks>net46</TargetFrameworks> with <TargetFrameworks>net47</TargetFrameworks>
Restore packages & rebuild
Notice build errors caused by absence of Remoting V1:
Error CS0234 The type or namespace name 'V1' does not exist in the namespace 'Microsoft.ServiceFabric.Services.Remoting' (are you missing an assembly reference?) 

Note: If I comment out the V1 ServicePartitionClient to get it to compile, when I run the app I get 'Method 'get_ServicePartitionClient' in type 'IServiceProxySample.TestServiceProxy`1' from assembly 'IServiceProxySample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

**Comment by MicahMcKittrick-MSFT** [comment]
@deepakjangid-MSFT @ashishnegi any update on this one?

**Comment by ashishnegi** [comment]
@festivus @keithbo This is fixed in latest released packages 6.2.274
Please have a look at [release](https://blogs.msdn.microsoft.com/azureservicefabric/2018/05/14/6-2-release-update/) notes for feature updates.
Thanks for your patience.

**Comment by festivus** [comment]
The problem is still there. Please see the latest sample at https://github.com/festivus/ServiceProxySample

**Comment by ashishnegi** [comment]
@festivus I am having a look. Our change is to removed `ref/netstandard2.0` folder from nupkg and have explicit folders for each framework specific version and one `netstandard2.0` folder under `lib`.

**Comment by keithbo** [comment]
@ashishnegi 
Id: Microsoft.ServiceFabric.Services.Remoting
Version: 3.1.247

* lib
  * net45
* ref
  * netstandard2.0
* runtimes
  * linux
    * lib
      * netstandard2.0
  * win
    * lib
      * net461
      * net462
      * net47
      * net471
      * netstandard2.0

**Comment by ashishnegi** [comment]
@keithbo I think we need to look at `3.1.274` .
But don't mind that. I think there is some misunderstanding. The change is not out yet. Apologies for confusion.
@amanbha Is there any changes in nupkgs for release 6.2 ?

**Comment by keithbo** [comment]
Looks like [6.2.283.9494](https://blogs.msdn.microsoft.com/azureservicefabric/2018/05/29/service-fabric-6-1-refresh-release-cu2/) came out yesterday and, at least for me, V1 remoting is now resolving in net461 targeted assemblies. I haven't tried net47 as none of my immediate projects use it, but given the ref folder no longer appears in the nupkg I assume it should work for other framework targets as well.

**Comment by ashishnegi** [comment]
@keithbo @festivus I verified with the sample repo shared and it is working with latest nupkg `6.2.283`.
I admit that this change took too long to come out. We appreciate your patience.
Closing the issue as @keithbo confirmed that it's working.
