### ISSUE TITLE
Add-AzureRmServiceFabricClusterCertificate: VMExtensionProvisioningError

### ISSUE THREAD

**Issue by Domhnall90** [Azure/service-fabric-issues#946]
Trying to add a secondary certificate to an existing cluster using this Add-AzureRmServiceFabricClusterCertificate and the following error is returned:

"... Code:VMExtensionProvisioningError, Message:VM has reported a failure when

processing extension 'xxxxxx'. Error message: "Cannot find certificate with 'FindByThumbprint'

'xxxxx' in store 'my'...." 

The thumbprint returned in the error message does not match the thumbprint of either the existing primary certificate or the secondary certificate. Any help would be appreciated.

I set up the cluster through the Azure portal to test swapping around certs. We have a cluster with a certificate due to expire and wish to add a secondary cert and swap using the steps outlined in the doc below:

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-security-update-certs-azure

**Comment by gorkar** [comment]
I am facing the same issue here

**Comment by Domhnall90** [comment]
The certificate which I am trying to add as a secondary is from a CA. The thumbprint looks to be that of the intermediate certificate

**Comment by juhacket** [comment]
This is fixed starting in AzureRM.ServiceFabric 0.3.2 (Azure PowerShell 5.5.0).
https://github.com/Azure/azure-powershell/pull/5576

**Comment by apoutney** [comment]
I have encountered this exact same issue, however I'm running this through the cloud shell in the azure portal.  I assumed this would have the latest versions of Azure PowerShell and AzureRM.ServiceFabric.

What am i missing?

**Comment by a-santamaria** [comment]
For people still having this issue, please use Az module instead of AzureRM. Az.ServiceFabric has the fix for this. 
You can unsintall AzureRM:  `Uninstall-Module AzureRm `   and install Az `Install-Module -Name Az`
As explained here: https://docs.microsoft.com/en-us/powershell/azure/migrate-from-azurerm-to-az
